#!/usr/bin/env python3
import re

def parse_signature(signature):
    """Parse function signature to extract return type and parameter names"""
    if not signature or '(' not in signature:
        return 'void', [], False

    # Extract return type (first word before the function name)
    # e.g., "void CBaseEntity::Kill()" -> "void"
    # e.g., "Vector CBaseEntity::GetOrigin()" -> "Vector"
    parts = signature.split('(')[0].strip().split()
    return_type = parts[0] if parts else 'void'

    # Extract parameters from signature
    match = re.search(r'\((.*?)\)', signature)
    if not match:
        return return_type, [], False

    params_str = match.group(1).strip()
    if not params_str or params_str == 'void':
        return return_type, [], False

    # Check for variadic function (...)
    is_variadic = '...' in params_str

    # Split by comma and extract parameter names
    params = []
    param_index = 0
    for param in params_str.split(','):
        param = param.strip()
        if not param or param == '...':
            continue

        # Extract parameter name (last word in the parameter declaration)
        # e.g., "Vector pos" -> "pos", "int x" -> "x"
        parts = param.split()
        if parts:
            param_name = parts[-1]
            # Remove any pointer/reference symbols
            param_name = param_name.replace('*', '').replace('&', '')

            # Check if parameter name is valid (no special characters)
            if '<' in param_name or '>' in param_name or not param_name.replace('_', '').isalnum():
                # Use generic parameter name
                param_name = f'arg{param_index}'

            params.append(param_name)
            param_index += 1

    return return_type, params, is_variadic

# Read vscript.txt
with open('vscript_function_info.txt', 'r') as f:
    content = f.read()

# Parse functions
functions = []
lines = content.split('\n')
i = 0
while i < len(lines):
    if lines[i].startswith('Function:'):
        func_name = lines[i].split('Function:')[1].strip()
        signature = ''
        description = ''

        if i + 1 < len(lines) and lines[i + 1].startswith('Signature:'):
            signature = lines[i + 1].split('Signature:')[1].strip()

        if i + 2 < len(lines) and lines[i + 2].startswith('Description:'):
            description = lines[i + 2].split('Description:')[1].strip()

        functions.append((func_name, signature, description))
        i += 1
    i += 1

# Group functions by class
classes = {}
global_funcs = []

for func_name, signature, description in functions:
    if '::' in func_name:
        class_name, method_name = func_name.split('::', 1)
        if class_name not in classes:
            classes[class_name] = []
        classes[class_name].append((method_name, signature, description))
    else:
        global_funcs.append((func_name, signature, description))

# Generate wrapper code
output = []

# Add header comment
output.append('/*')
output.append(' * VScript Function Wrappers')
output.append(' * ')
output.append(' * This file wraps all VScript functions to make them accessible via LookupFunction().')
output.append(' * ')
output.append(' * Background:')
output.append(' * - C++ bound functions (userdata) cannot be found by LookupFunction()')
output.append(' * - Only Squirrel-defined functions can be looked up by name')
output.append(' * - This wrapper library solves this by wrapping all VScript functions in Squirrel functions')
output.append(' * ')
output.append(' * Usage:')
output.append(' * 1. Load this file in your VScript: DoIncludeScript("vscript_wrappers.nut", getroottable())')
output.append(' * 2. Access functions via API tables: CDirectorAPI.GetGameMode(), ConvarsAPI.GetFloat("sv_cheats"), etc.')
output.append(' * 3. Use LookupFunction() to get function handles for SourcePawn')
output.append(' * ')
output.append(' * Auto-generated by generate_wrappers.py - Do not edit manually')
output.append(' */')
output.append('')

# Generate class wrappers
for class_name in sorted(classes.keys()):
    api_name = class_name + 'API'
    output.append(f'{api_name} <- {{')

    methods = classes[class_name]
    for i, (method_name, signature, description) in enumerate(methods):
        return_type, params, is_variadic = parse_signature(signature)
        is_void = return_type.lower() == 'void'

        # Add comments
        if description:
            output.append(f'    // {description}')
        output.append(f'    // Returns: {return_type}')

        # For variadic functions, use acall with correct pattern
        if is_variadic:
            if class_name in ['CDirector', 'CNavMesh', 'CEntities', 'CNetPropManager', 'CScriptEntityOutputs', 'CScriptResponseCriteria', 'Convars', 'Decider']:
                instance_map = {
                    'CDirector': 'Director',
                    'CNavMesh': 'NavMesh',
                    'CEntities': 'Entities',
                    'CNetPropManager': 'NetProps',
                    'CScriptEntityOutputs': 'EntityOutputs',
                    'CScriptResponseCriteria': 'ResponseCriteria',
                    'Convars': 'Convars',
                    'Decider': 'Decider'
                }
                instance_name = instance_map.get(class_name, class_name)
                params_str = ', '.join(params) if params else ''
                variadic_params = params_str + (', ' if params_str else '') + '...'

                if is_void:
                    output.append(f'    {method_name} = function({variadic_params}) {{')
                    if params:
                        output.append(f'        local args = [::{instance_name}, {params_str}]; args.extend(vargv)')
                    else:
                        output.append(f'        local args = [::{instance_name}]; args.extend(vargv)')
                    output.append(f'        ::{instance_name}.{method_name}.acall(args)')
                    output.append(f'    }},')
                else:
                    output.append(f'    {method_name} = function({variadic_params}) {{')
                    if params:
                        output.append(f'        local args = [::{instance_name}, {params_str}]; args.extend(vargv)')
                    else:
                        output.append(f'        local args = [::{instance_name}]; args.extend(vargv)')
                    output.append(f'        return ::{instance_name}.{method_name}.acall(args)')
                    output.append(f'    }},')
            else:
                output.append(f'    // Variadic instance method - use entity.{method_name}() directly')
            continue

        # Generate wrapper
        if class_name in ['CDirector', 'CNavMesh', 'CEntities', 'CNetPropManager', 'CScriptEntityOutputs', 'CScriptResponseCriteria', 'Convars', 'Decider']:
            # Singleton classes - call on the global instance
            # Map class names to their global instance names
            instance_map = {
                'CDirector': 'Director',
                'CNavMesh': 'NavMesh',
                'CEntities': 'Entities',
                'CNetPropManager': 'NetProps',
                'CScriptEntityOutputs': 'EntityOutputs',
                'CScriptResponseCriteria': 'ResponseCriteria',
                'Convars': 'Convars',
                'Decider': 'Decider'
            }
            instance_name = instance_map.get(class_name, class_name)
            if not params:
                if is_void:
                    output.append(f'    {method_name} = function() {{ {instance_name}.{method_name}() }},')
                else:
                    output.append(f'    {method_name} = function() {{ return {instance_name}.{method_name}() }},')
            else:
                params_str = ', '.join(params)
                if is_void:
                    output.append(f'    {method_name} = function({params_str}) {{ {instance_name}.{method_name}({params_str}) }},')
                else:
                    output.append(f'    {method_name} = function({params_str}) {{ return {instance_name}.{method_name}({params_str}) }},')
        else:
            # Instance methods - need entity parameter
            if not params:
                if is_void:
                    output.append(f'    {method_name} = function(entity) {{ entity.{method_name}() }},')
                else:
                    output.append(f'    {method_name} = function(entity) {{ return entity.{method_name}() }},')
            else:
                params_str = ', '.join(params)
                if is_void:
                    output.append(f'    {method_name} = function(entity, {params_str}) {{ entity.{method_name}({params_str}) }},')
                else:
                    output.append(f'    {method_name} = function(entity, {params_str}) {{ return entity.{method_name}({params_str}) }},')

    # Remove trailing comma from last item
    if output[-1].endswith(','):
        output[-1] = output[-1][:-1]

    output.append('}')
    output.append('')

# Generate global functions wrapper
output.append('GlobalAPI <- {')
for i, (func_name, signature, description) in enumerate(global_funcs):
    return_type, params, is_variadic = parse_signature(signature)
    is_void = return_type.lower() == 'void'

    # Add comments
    if description:
        output.append(f'    // {description}')
    output.append(f'    // Returns: {return_type}')

    # For variadic functions, use acall with correct pattern
    if is_variadic:
        params_str = ', '.join(params) if params else ''
        variadic_params = params_str + (', ' if params_str else '') + '...'

        if is_void:
            output.append(f'    {func_name} = function({variadic_params}) {{')
            if params:
                output.append(f'        local args = [null, {params_str}]; args.extend(vargv)')
            else:
                output.append(f'        local args = [null]; args.extend(vargv)')
            output.append(f'        ::{func_name}.acall(args)')
            output.append(f'    }},')
        else:
            output.append(f'    {func_name} = function({variadic_params}) {{')
            if params:
                output.append(f'        local args = [null, {params_str}]; args.extend(vargv)')
            else:
                output.append(f'        local args = [null]; args.extend(vargv)')
            output.append(f'        return ::{func_name}.acall(args)')
            output.append(f'    }},')
        continue

    if not params:
        if is_void:
            output.append(f'    {func_name} = function() {{ ::{func_name}() }},')
        else:
            output.append(f'    {func_name} = function() {{ return ::{func_name}() }},')
    else:
        params_str = ', '.join(params)
        if is_void:
            output.append(f'    {func_name} = function({params_str}) {{ ::{func_name}({params_str}) }},')
        else:
            output.append(f'    {func_name} = function({params_str}) {{ return ::{func_name}({params_str}) }},')

# Remove trailing comma
if output[-1].endswith(','):
    output[-1] = output[-1][:-1]

output.append('}')

# Write output
with open('vscript_wrappers.nut', 'w') as f:
    f.write('\n'.join(output))

print(f'Generated wrappers for {len(functions)} functions')
print(f'Classes: {len(classes)}')
print(f'Global functions: {len(global_funcs)}')
