/*
 * VScript Function Wrappers
 * 
 * This file wraps all VScript functions to make them accessible via LookupFunction().
 * 
 * Background:
 * - C++ bound functions (userdata) cannot be found by LookupFunction()
 * - Only Squirrel-defined functions can be looked up by name
 * - This wrapper library solves this by wrapping all VScript functions in Squirrel functions
 * 
 * Usage:
 * 1. Load this file in your VScript: DoIncludeScript("vscript_wrappers.nut", getroottable())
 * 2. Access functions via API tables: CDirectorAPI.GetGameMode(), ConvarsAPI.GetFloat("sv_cheats"), etc.
 * 3. Use LookupFunction() to get function handles for SourcePawn
 * 
 * Auto-generated by generate_wrappers.py - Do not edit manually
 */

CBaseAnimatingAPI <- {
    // Find a bodygroup id by name
    // Returns: int
    FindBodygroupByName = function(entity, string) { return entity.FindBodygroupByName(string) },
    // Get the attachement id's angles as a p,y,r vector
    // Returns: QAngle
    GetAttachmentAngles = function(entity, int) { return entity.GetAttachmentAngles(int) },
    // Get the named attachement's parent bone index
    // Returns: int
    GetAttachmentBone = function(entity, int) { return entity.GetAttachmentBone(int) },
    // Get the attachement id's origin vector
    // Returns: Vector
    GetAttachmentOrigin = function(entity, int) { return entity.GetAttachmentOrigin(int) },
    // Get a bodygroup by id
    // Returns: int
    GetBodygroup = function(entity, int) { return entity.GetBodygroup(int) },
    // Get the bodygroup id's name
    // Returns: string
    GetBodygroupName = function(entity, int) { return entity.GetBodygroupName(int) },
    // Get name by group and part
    // Returns: string
    GetBodygroupPartName = function(entity, int, int) { return entity.GetBodygroupPartName(int, int) },
    // Get the bone id's angles as a p,y,r vector
    // Returns: QAngle
    GetBoneAngles = function(entity, int) { return entity.GetBoneAngles(int) },
    // Get the bone id's origin vector
    // Returns: Vector
    GetBoneOrigin = function(entity, int) { return entity.GetBoneOrigin(int) },
    // Returns: float
    GetModelScale = function(entity) { return entity.GetModelScale() },
    // Get the current sequence id
    // Returns: int
    GetSequence = function(entity) { return entity.GetSequence() },
    // Get the activity name for a sequence by id
    // Returns: string
    GetSequenceActivityName = function(entity, int) { return entity.GetSequenceActivityName(int) },
    // Get a sequence duration by id
    // Returns: float
    GetSequenceDuration = function(entity, int) { return entity.GetSequenceDuration(int) },
    // Get a sequence name by id
    // Returns: string
    GetSequenceName = function(entity, int) { return entity.GetSequenceName(int) },
    // Ask whether the main sequence is done playing
    // Returns: bool
    IsSequenceFinished = function(entity) { return entity.IsSequenceFinished() },
    // Get the named activity index
    // Returns: int
    LookupActivity = function(entity, string) { return entity.LookupActivity(string) },
    // Get the named attachement id
    // Returns: int
    LookupAttachment = function(entity, string) { return entity.LookupAttachment(string) },
    // Get the named bone index
    // Returns: int
    LookupBone = function(entity, string) { return entity.LookupBone(string) },
    // Looks up a sequence by sequence name or activity name
    // Returns: int
    LookupSequence = function(entity, string) { return entity.LookupSequence(string) },
    // Reset a sequence by id. If the id is different than the current sequence, switch to the new sequence
    // Returns: void
    ResetSequence = function(entity, int) { entity.ResetSequence(int) },
    // Sets a bodygroup
    // Returns: void
    SetBodygroup = function(entity, int, int) { entity.SetBodygroup(int, int) },
    // (scale, change_duration) Changes a model's scale over time
    // Returns: void
    SetModelScale = function(entity, float, float) { entity.SetModelScale(float, float) },
    // (id, value) Sets a pose parameter value
    // Returns: float
    SetPoseParameter = function(entity, int, float) { return entity.SetPoseParameter(int, float) },
    // Set a sequence by id
    // Returns: void
    SetSequence = function(entity, int) { entity.SetSequence(int) }
}

CBaseEntityAPI <- {
    // Apply a Velocity Impulse
    // Returns: void
    ApplyAbsVelocityImpulse = function(entity, Vector) { entity.ApplyAbsVelocityImpulse(Vector) },
    // Apply an Ang Velocity Impulse
    // Returns: void
    ApplyLocalAngularVelocityImpulse = function(entity, Vector) { entity.ApplyLocalAngularVelocityImpulse(Vector) },
    // Adds an I/O connection that will call the named function when the specified output fires
    // Returns: void
    ConnectOutput = function(entity, string, string) { entity.ConnectOutput(string, string) },
    // Removes a connected script function from an I/O event.
    // Returns: void
    DisconnectOutput = function(entity, string, string) { entity.DisconnectOutput(string, string) },
    // Returns: handle
    FirstMoveChild = function(entity) { return entity.FirstMoveChild() },
    // Returns: QAngle
    GetAngles = function(entity) { return entity.GetAngles() },
    // Get Base? velocity
    // Returns: Vector
    GetBaseVelocity = function(entity) { return entity.GetBaseVelocity() },
    // Get world space center of object - absolute coords
    // Returns: Vector
    GetCenter = function(entity) { return entity.GetCenter() },
    // Returns: string
    GetClassname = function(entity) { return entity.GetClassname() },
    // GetContext( name ): looks up a context and returns it if available. May return string, float, or null (if the context isn't found)
    // Returns: <unknown>
    GetContext = function(entity, string) { return entity.GetContext(string) },
    // Get the entity as an EHANDLE
    // Returns: <unknown>
    GetEntityHandle = function(entity) { return entity.GetEntityHandle() },
    // Returns: int
    GetEntityIndex = function(entity) { return entity.GetEntityIndex() },
    // Get the forward vector of the entity
    // Returns: Vector
    GetForwardVector = function(entity) { return entity.GetForwardVector() },
    // Returns: int
    GetHealth = function(entity) { return entity.GetHealth() },
    // Returns: QAngle
    GetLocalAngles = function(entity) { return entity.GetLocalAngles() },
    // Maybe local angvel
    // Returns: QAngle
    GetLocalAngularVelocity = function(entity) { return entity.GetLocalAngularVelocity() },
    // Returns: Vector
    GetLocalOrigin = function(entity) { return entity.GetLocalOrigin() },
    // Get Entity relative velocity
    // Returns: Vector
    GetLocalVelocity = function(entity) { return entity.GetLocalVelocity() },
    // Returns: int
    GetMaxHealth = function(entity) { return entity.GetMaxHealth() },
    // Returns: string
    GetModelName = function(entity) { return entity.GetModelName() },
    // If in hierarchy, retrieves the entity's parent
    // Returns: handle
    GetMoveParent = function(entity) { return entity.GetMoveParent() },
    // Returns: string
    GetName = function(entity) { return entity.GetName() },
    // Returns: Vector
    GetOrigin = function(entity) { return entity.GetOrigin() },
    // Get the owner entity, if there is one
    // Returns: handle
    GetOwnerEntity = function(entity) { return entity.GetOwnerEntity() },
    // Get the entity name stripped of template unique decoration
    // Returns: string
    GetPreTemplateName = function(entity) { return entity.GetPreTemplateName() },
    // If in hierarchy, walks up the hierarchy to find the root parent
    // Returns: handle
    GetRootMoveParent = function(entity) { return entity.GetRootMoveParent() },
    // Retrieve the unique identifier used to refer to the entity within the scripting system
    // Returns: string
    GetScriptId = function(entity) { return entity.GetScriptId() },
    // Retrieve the script-side data associated with an entity
    // Returns: handle
    GetScriptScope = function(entity) { return entity.GetScriptScope() },
    // Returns: Vector
    GetVelocity = function(entity) { return entity.GetVelocity() },
    // Returns: bool
    IsPlayer = function(entity) { return entity.IsPlayer() },
    // Returns: void
    Kill = function(entity) { entity.Kill() },
    // Returns: handle
    NextMovePeer = function(entity) { return entity.NextMovePeer() },
    // Takes duration, value for a temporary override
    // Returns: void
    OverrideFriction = function(entity, float, float) { entity.OverrideFriction(float, float) },
    // Returns: int
    PrecacheModel = function(entity, string) { return entity.PrecacheModel(string) },
    // Returns: void
    PrecacheScriptSound = function(entity, string) { entity.PrecacheScriptSound(string) },
    // Returns: void
    SetAngles = function(entity, QAngle) { entity.SetAngles(QAngle) },
    // SetContext( name , value, duration ): store any key/value pair in this entity's dialog contexts. Value must be a string. Will last for duration (set -1 to mean 'forever').
    // Returns: void
    SetContext = function(entity, string, string, float) { entity.SetContext(string, string, float) },
    // SetContext( name , value, duration ): store any key/value pair in this entity's dialog contexts. Value must be a number (int or float). Will last for duration (set -1 to mean 'forever').
    // Returns: void
    SetContextNum = function(entity, string, float, float) { entity.SetContextNum(string, float, float) },
    // Set the orientation of the entity to have this forward vector
    // Returns: void
    SetForwardVector = function(entity, Vector) { entity.SetForwardVector(Vector) },
    // Set PLAYER friction, ignored for objects
    // Returns: void
    SetFriction = function(entity, float) { entity.SetFriction(float) },
    // Set PLAYER gravity, ignored for objects
    // Returns: void
    SetGravity = function(entity, float) { entity.SetGravity(float) },
    // Returns: void
    SetHealth = function(entity, int) { entity.SetHealth(int) },
    // Returns: void
    SetLocalAngles = function(entity, QAngle) { entity.SetLocalAngles(QAngle) },
    // Returns: void
    SetLocalOrigin = function(entity, Vector) { entity.SetLocalOrigin(Vector) },
    // Returns: void
    SetMaxHealth = function(entity, int) { entity.SetMaxHealth(int) },
    // Set a model for this entity
    // Returns: void
    SetModel = function(entity, string) { entity.SetModel(string) },
    // Returns: void
    SetOrigin = function(entity, Vector) { entity.SetOrigin(Vector) },
    // Returns: void
    SetVelocity = function(entity, Vector) { entity.SetVelocity(Vector) },
    // (flDamage, nDamageType, hAttacker)
    // Returns: void
    TakeDamage = function(entity, float, int, handle) { entity.TakeDamage(float, int, handle) },
    // (hInflictor, hAttacker, hWeapon, vecDamageForce, vecDamagePosition, flDamage, nDamageType)
    // Returns: void
    TakeDamageEx = function(entity, handle, handle, handle, Vector, Vector, float, int) { entity.TakeDamageEx(handle, handle, handle, Vector, Vector, float, int) },
    // Ensure that an entity's script scope has been created
    // Returns: bool
    ValidateScriptScope = function(entity) { return entity.ValidateScriptScope() }
}

CBaseFlexAPI <- {
    // Returns the instance of the oldest active scene entity (if any).
    // Returns: handle
    GetCurrentScene = function(entity) { return entity.GetCurrentScene() },
    // Returns the instance of the scene entity at the specified index.
    // Returns: handle
    GetSceneByIndex = function(entity, int) { return entity.GetSceneByIndex(int) },
    // Play the specified .vcd file.
    // Returns: float
    PlayScene = function(entity, string, float) { return entity.PlayScene(string, float) }
}

CDirectorAPI <- {
    // Returns true if all Survivors are in the battlefield
    // Returns: bool
    AreAllSurvivorsInBattlefield = function() { return Director.AreAllSurvivorsInBattlefield() },
    // True when all survivors are within the finale area
    // Returns: bool
    AreAllSurvivorsInFinaleArea = function() { return Director.AreAllSurvivorsInFinaleArea() },
    // True when teams are flipped in Versus modes
    // Returns: bool
    AreTeamsFlipped = function() { return Director.AreTeamsFlipped() },
    // Mark all cached bot query results as invalid
    // Returns: void
    ClearCachedBotQueries = function() { Director.ClearCachedBotQueries() },
    // Push the ScriptedMode to next stage - i.e. request GNSS be called
    // Returns: void
    ForceNextStage = function() { Director.ForceNextStage() },
    // Get the distance between the lead and trailing survivors, smoothed over time
    // Returns: float
    GetAveragedSurvivorSpan = function() { return Director.GetAveragedSurvivorSpan() },
    // Get the rate at which the lead survivor is moving along the flow, smoothed over time
    // Returns: float
    GetAveragedSurvivorSpeed = function() { return Director.GetAveragedSurvivorSpeed() },
    // Returns the closest active pipe bomb from this origin
    // Returns: handle
    GetClosestActivePipeBomb = function(Vector) { return Director.GetClosestActivePipeBomb(Vector) },
    // Returns the closest character who is IT
    // Returns: handle
    GetClosestCharacterWhoIsIT = function(handle) { return Director.GetClosestCharacterWhoIsIT(handle) },
    // Returns the closest Survivor to the passed origin
    // Returns: handle
    GetClosestSurvivor = function(Vector, bool, bool) { return Director.GetClosestSurvivor(Vector, bool, bool) },
    // Returns number fo infected currently spawned
    // Returns: int
    GetCommonInfectedCount = function() { return Director.GetCommonInfectedCount() },
    // Get the maximum distance along the flow that the survivors have reached
    // Returns: float
    GetFurthestSurvivorFlow = function() { return Director.GetFurthestSurvivorFlow() },
    // Get the current game mode
    // Returns: string
    GetGameMode = function() { return Director.GetGameMode() },
    // Get the current base game mode
    // Returns: string
    GetGameModeBase = function() { return Director.GetGameModeBase() },
    // Returns the Survivor with the highest flow
    // Returns: handle
    GetHighestFlowSurvivor = function() { return Director.GetHighestFlowSurvivor() },
    // Get the end time of the cooldown timer
    // Returns: float
    GetHoldoutCooldownEndTime = function() { return Director.GetHoldoutCooldownEndTime() },
    // Returns the Survivor with the lowest flow
    // Returns: handle
    GetLowestFlowSurvivor = function() { return Director.GetLowestFlowSurvivor() },
    // Get the current game mode
    // Returns: string
    GetMapName = function() { return Director.GetMapName() },
    // Return the current map number
    // Returns: int
    GetMapNumber = function() { return Director.GetMapNumber() },
    // Returns the current number of mission wipes
    // Returns: int
    GetMissionWipes = function() { return Director.GetMissionWipes() },
    // Returns tnumber of infected waiting to spawn
    // Returns: int
    GetPendingMobCount = function() { return Director.GetPendingMobCount() },
    // Returns a random Survivor
    // Returns: handle
    GetRandomSurvivor = function() { return Director.GetRandomSurvivor() },
    // 1=L4D1 Survivors, 2=L4D2 Survivors
    // Returns: int
    GetSurvivorSet = function() { return Director.GetSurvivorSet() },
    // Returns the time since the passed zombie type was killed
    // Returns: float
    GetTimeSinceSpecialZombieKilled = function(int) { return Director.GetTimeSinceSpecialZombieKilled(int) },
    // Returns the total elapsed mission time
    // Returns: int
    GetTotalElapsedMissionTime = function() { return Director.GetTotalElapsedMissionTime() },
    // True when one or more survivors have left the starting safe area
    // Returns: bool
    HasAnySurvivorLeftSafeArea = function() { return Director.HasAnySurvivorLeftSafeArea() },
    // True when one or more survivors are bypassing the Tank
    // Returns: bool
    IsAnySurvivorBypassingTank = function() { return Director.IsAnySurvivorBypassingTank() },
    // Returns true if any survivor recently dealt or took damage
    // Returns: bool
    IsAnySurvivorInCombat = function() { return Director.IsAnySurvivorInCombat() },
    // True when one or more survivors are in the exit checkpoint
    // Returns: bool
    IsAnySurvivorInExitCheckpoint = function() { return Director.IsAnySurvivorInExitCheckpoint() },
    // True when one or more survivors are in the starting safe area
    // Returns: bool
    IsAnySurvivorInStartArea = function() { return Director.IsAnySurvivorInStartArea() },
    // True when the finale has started
    // Returns: bool
    IsFinale = function() { return Director.IsFinale() },
    // True when the finale escape is in progress
    // Returns: bool
    IsFinaleEscapeInProgress = function() { return Director.IsFinaleEscapeInProgress() },
    // True when the finale vehicle is ready
    // Returns: bool
    IsFinaleVehicleReady = function() { return Director.IsFinaleVehicleReady() },
    // Returns true if the finale has been won
    // Returns: bool
    IsFinaleWon = function() { return Director.IsFinaleWon() },
    // True if the first map in a scenario
    // Returns: bool
    IsFirstMapInScenario = function() { return Director.IsFirstMapInScenario() },
    // Return true is the current campaign is originally from L4D1
    // Returns: bool
    IsL4D1Campaign = function() { return Director.IsL4D1Campaign() },
    // Returns true if the passed location is fogged to Survivors
    // Returns: bool
    IsLocationFoggedToSurvivors = function(Vector) { return Director.IsLocationFoggedToSurvivors(Vector) },
    // True if the intro is currently playing
    // Returns: bool
    IsPlayingIntro = function() { return Director.IsPlayingIntro() },
    // Return true if game is running on a console (such as Xbox 360)
    // Returns: bool
    IsPlayingOnConsole = function() { return Director.IsPlayingOnConsole() },
    // True if the map is the start of the session
    // Returns: bool
    IsSessionStartMap = function() { return Director.IsSessionStartMap() },
    // Return true if game is in single player
    // Returns: bool
    IsSinglePlayerGame = function() { return Director.IsSinglePlayerGame() },
    // Returns true if any tanks are aggro on survivors
    // Returns: bool
    IsTankInPlay = function() { return Director.IsTankInPlay() },
    // Let the L4D1 survivors know that now is a good time to give the players an item
    // Returns: void
    L4D1SurvivorGiveItem = function() { Director.L4D1SurvivorGiveItem() },
    // Plays a horde scream sound and asks survivors to speak 'incoming horde' lines
    // Returns: void
    PlayMegaMobWarningSounds = function() { Director.PlayMegaMobWarningSounds() },
    // Registers a target entity as forbidden
    // Returns: void
    RegisterForbiddenTarget = function(handle) { Director.RegisterForbiddenTarget(handle) },
    // Trigger a mob as soon as possible when in BUILD_UP
    // Returns: void
    ResetMobTimer = function() { Director.ResetMobTimer() },
    // Reset all special timers (by type and by slot) so that hopefully mobs will spawn asap
    // Returns: void
    ResetSpecialTimers = function() { Director.ResetSpecialTimers() },
    // Set the end time of the cooldown timer
    // Returns: void
    SetHoldoutCooldownEndTime = function(float) { Director.SetHoldoutCooldownEndTime(float) },
    // Unregisters a target entity as forbidden
    // Returns: void
    UnregisterForbiddenTarget = function(handle) { Director.UnregisterForbiddenTarget(handle) },
    // generic user defined event fired from a squirrel script
    // Returns: void
    UserDefinedEvent1 = function() { Director.UserDefinedEvent1() },
    // generic user defined event fired from a squirrel script
    // Returns: void
    UserDefinedEvent2 = function() { Director.UserDefinedEvent2() },
    // generic user defined event fired from a squirrel script
    // Returns: void
    UserDefinedEvent3 = function() { Director.UserDefinedEvent3() },
    // generic user defined event fired from a squirrel script
    // Returns: void
    UserDefinedEvent4 = function() { Director.UserDefinedEvent4() },
    // Warp the survivors to the crescendo event
    // Returns: void
    WarpAllSurvivorsToBattlefield = function() { Director.WarpAllSurvivorsToBattlefield() },
    // Warp the survivors to the next checkpoint
    // Returns: void
    WarpAllSurvivorsToCheckpoint = function() { Director.WarpAllSurvivorsToCheckpoint() },
    // Warp the survivors to the finale area
    // Returns: void
    WarpAllSurvivorsToFinale = function() { Director.WarpAllSurvivorsToFinale() }
}

CEntitiesAPI <- {
    // Find entities by class name. Pass 'null' to start an iteration, or reference to a previously found entity to continue a search
    // Returns: handle
    FindByClassname = function(handle, string) { return Entities.FindByClassname(handle, string) },
    // Find entities by class name nearest to a point.
    // Returns: handle
    FindByClassnameNearest = function(string, Vector, float) { return Entities.FindByClassnameNearest(string, Vector, float) },
    // Find entities by class name within a radius. Pass 'null' to start an iteration, or reference to a previously found entity to continue a search
    // Returns: handle
    FindByClassnameWithin = function(handle, string, Vector, float) { return Entities.FindByClassnameWithin(handle, string, Vector, float) },
    // Find entities by model name. Pass 'null' to start an iteration, or reference to a previously found entity to continue a search
    // Returns: handle
    FindByModel = function(handle, string) { return Entities.FindByModel(handle, string) },
    // Find entities by name. Pass 'null' to start an iteration, or reference to a previously found entity to continue a search
    // Returns: handle
    FindByName = function(handle, string) { return Entities.FindByName(handle, string) },
    // Find entities by name nearest to a point.
    // Returns: handle
    FindByNameNearest = function(string, Vector, float) { return Entities.FindByNameNearest(string, Vector, float) },
    // Find entities by name within a radius. Pass 'null' to start an iteration, or reference to a previously found entity to continue a search
    // Returns: handle
    FindByNameWithin = function(handle, string, Vector, float) { return Entities.FindByNameWithin(handle, string, Vector, float) },
    // Find entities by targetname. Pass 'null' to start an iteration, or reference to a previously found entity to continue a search
    // Returns: handle
    FindByTarget = function(handle, string) { return Entities.FindByTarget(handle, string) },
    // Find entities within a radius. Pass 'null' to start an iteration, or reference to a previously found entity to continue a search
    // Returns: handle
    FindInSphere = function(handle, Vector, float) { return Entities.FindInSphere(handle, Vector, float) },
    // Begin an iteration over the list of entities
    // Returns: handle
    First = function() { return Entities.First() },
    // Continue an iteration over the list of entities, providing reference to a previously found entity
    // Returns: handle
    Next = function(handle) { return Entities.Next(handle) }
}

CNavMeshAPI <- {
    // Arguments: ( startpos, endpos, ignoreArea ) - get nav ladder from ray
    // Returns: handle
    FindLadderAlongRay = function(Vector, Vector, handle) { return NavMesh.FindLadderAlongRay(Vector, Vector, handle) },
    // Arguments: ( startpos, endpos, ignoreAreaID ) - get nav area from ray
    // Returns: handle
    FindNavAreaAlongRay = function(Vector, Vector, handle) { return NavMesh.FindNavAreaAlongRay(Vector, Vector, handle) },
    // Arguments: ( table ) - fills a passed in table of all nav areas
    // Returns: void
    GetAllAreas = function(handle) { NavMesh.GetAllAreas(handle) },
    // Arguments: ( table ) - fills a passed in table of all nav ladders
    // Returns: void
    GetAllLadders = function(handle) { NavMesh.GetAllLadders(handle) },
    // Arguments: ( bits, table ) - fills a passed in table of all nav areas that have the specified attributes
    // Returns: void
    GetAreasWithAttributes = function(int, handle) { NavMesh.GetAreasWithAttributes(int, handle) },
    // Arguments: ( ladderID ) - get nav ladder by ID
    // Returns: handle
    GetLadderByID = function(int) { return NavMesh.GetLadderByID(int) },
    // return total number of nav ladders
    // Returns: int
    GetLadderCount = function() { return NavMesh.GetLadderCount() },
    // Arguments: ( origin, flBeneath ) - given a position in the world, return the nav area that is closest to or below that height.
    // Returns: handle
    GetNavArea = function(Vector, float) { return NavMesh.GetNavArea(Vector, float) },
    // Arguments: ( areaID ) - get nav area by ID
    // Returns: handle
    GetNavAreaByID = function(int) { return NavMesh.GetNavAreaByID(int) },
    // return total number of nav areas
    // Returns: int
    GetNavAreaCount = function() { return NavMesh.GetNavAreaCount() },
    // Arguments: ( table ) - Fills the table with areas from a path. Returns whether a path was found
    // Returns: bool
    GetNavAreasFromBuildPath = function(handle, handle, Vector, float, int, bool, handle) { return NavMesh.GetNavAreasFromBuildPath(handle, handle, Vector, float, int, bool, handle) },
    // Arguments: ( origin, radius, table ) - fills a passed in table of nav areas within radius
    // Returns: void
    GetNavAreasInRadius = function(Vector, float, handle) { NavMesh.GetNavAreasInRadius(Vector, float, handle) },
    // Arguments: ( entity, table ) - fills passed in table with areas overlapping entity's extent
    // Returns: void
    GetNavAreasOverlappingEntityExtent = function(handle, handle) { NavMesh.GetNavAreasOverlappingEntityExtent(handle, handle) },
    // Arguments: ( origin, maxDist, checkLOS, checkGround ) - given a position in the world, return the nav area that is closest to or below that height.
    // Returns: handle
    GetNearestNavArea = function(Vector, float, bool, bool) { return NavMesh.GetNearestNavArea(Vector, float, bool, bool) },
    // Arguments: ( table ) - fills a passed in table of all obstructing entities
    // Returns: void
    GetObstructingEntities = function(handle) { NavMesh.GetObstructingEntities(handle) },
    // Arguments: ( area, area, goalPos, flMaxPathLength, teamID, ignoreNavBlockers ) - returns true if a path exists
    // Returns: bool
    NavAreaBuildPath = function(handle, handle, Vector, float, int, bool) { return NavMesh.NavAreaBuildPath(handle, handle, Vector, float, int, bool) },
    // Arguments: ( area, area, flMaxPathLength ) - compute distance between two areas. Return -1 if can't reach 'endArea' from 'startArea'
    // Returns: float
    NavAreaTravelDistance = function(handle, handle, float) { return NavMesh.NavAreaTravelDistance(handle, handle, float) },
    // Arguments: ( entity ) - registers avoidance obstacle
    // Returns: void
    RegisterAvoidanceObstacle = function(handle) { NavMesh.RegisterAvoidanceObstacle(handle) },
    // Unblock the rescue vehicle nav areas so bots can path through them
    // Returns: void
    UnblockRescueVehicleNav = function() { NavMesh.UnblockRescueVehicleNav() },
    // Arguments: ( entity ) - unregisters avoidance obstacle
    // Returns: void
    UnregisterAvoidanceObstacle = function(handle) { NavMesh.UnregisterAvoidanceObstacle(handle) }
}

CNetPropManagerAPI <- {
    // Arguments: ( entity, propertyName )
    // Returns: int
    GetPropArraySize = function(handle, string) { return NetProps.GetPropArraySize(handle, string) },
    // Arguments: ( entity, propertyName ) - returns an entity
    // Returns: handle
    GetPropEntity = function(handle, string) { return NetProps.GetPropEntity(handle, string) },
    // Arguments: ( entity, propertyName, arrayElement ) - returns an entity
    // Returns: handle
    GetPropEntityArray = function(handle, string, int) { return NetProps.GetPropEntityArray(handle, string, int) },
    // Arguments: ( entity, propertyName )
    // Returns: float
    GetPropFloat = function(handle, string) { return NetProps.GetPropFloat(handle, string) },
    // Arguments: ( entity, propertyName, arrayElement )
    // Returns: float
    GetPropFloatArray = function(handle, string, int) { return NetProps.GetPropFloatArray(handle, string, int) },
    // Arguments: ( entity, propertyName )
    // Returns: int
    GetPropInt = function(handle, string) { return NetProps.GetPropInt(handle, string) },
    // Arguments: ( entity, propertyName, arrayElement )
    // Returns: int
    GetPropIntArray = function(handle, string, int) { return NetProps.GetPropIntArray(handle, string, int) },
    // Arguments: ( entity, propertyName )
    // Returns: string
    GetPropString = function(handle, string) { return NetProps.GetPropString(handle, string) },
    // Arguments: ( entity, propertyName, arrayElement )
    // Returns: string
    GetPropStringArray = function(handle, string, int) { return NetProps.GetPropStringArray(handle, string, int) },
    // Arguments: ( entity, propertyName ) - return the prop type as a string
    // Returns: string
    GetPropType = function(handle, string) { return NetProps.GetPropType(handle, string) },
    // Arguments: ( entity, propertyName )
    // Returns: Vector
    GetPropVector = function(handle, string) { return NetProps.GetPropVector(handle, string) },
    // Arguments: ( entity, propertyName, arrayElement )
    // Returns: Vector
    GetPropVectorArray = function(handle, string, int) { return NetProps.GetPropVectorArray(handle, string, int) },
    // Arguments: ( entity, propertyName )
    // Returns: bool
    HasProp = function(handle, string) { return NetProps.HasProp(handle, string) },
    // Arguments: ( entity, propertyName, value )
    // Returns: void
    SetPropEntity = function(handle, string, handle) { NetProps.SetPropEntity(handle, string, handle) },
    // Arguments: ( entity, propertyName, value, arrayElement )
    // Returns: void
    SetPropEntityArray = function(handle, string, handle, int) { NetProps.SetPropEntityArray(handle, string, handle, int) },
    // Arguments: ( entity, propertyName, value )
    // Returns: void
    SetPropFloat = function(handle, string, float) { NetProps.SetPropFloat(handle, string, float) },
    // Arguments: ( entity, propertyName, value, arrayElement )
    // Returns: void
    SetPropFloatArray = function(handle, string, float, int) { NetProps.SetPropFloatArray(handle, string, float, int) },
    // Arguments: ( entity, propertyName, value )
    // Returns: void
    SetPropInt = function(handle, string, int) { NetProps.SetPropInt(handle, string, int) },
    // Arguments: ( entity, propertyName, value, arrayElement )
    // Returns: void
    SetPropIntArray = function(handle, string, int, int) { NetProps.SetPropIntArray(handle, string, int, int) },
    // Arguments: ( entity, propertyName, value )
    // Returns: void
    SetPropString = function(handle, string, string) { NetProps.SetPropString(handle, string, string) },
    // Arguments: ( entity, propertyName, value, arrayElement )
    // Returns: void
    SetPropStringArray = function(handle, string, string, int) { NetProps.SetPropStringArray(handle, string, string, int) },
    // Arguments: ( entity, propertyName, value )
    // Returns: void
    SetPropVector = function(handle, string, Vector) { NetProps.SetPropVector(handle, string, Vector) },
    // Arguments: ( entity, propertyName, value, arrayElement )
    // Returns: void
    SetPropVectorArray = function(handle, string, Vector, int) { NetProps.SetPropVectorArray(handle, string, Vector, int) }
}

CScriptEntityOutputsAPI <- {
    // Arguments: ( entity, outputName, targetName, inputName, parameter, delay, timesToFire ) - add a new output to the entity
    // Returns: void
    AddOutput = function(handle, string, string, string, string, float, int) { EntityOutputs.AddOutput(handle, string, string, string, string, float, int) },
    // Arguments: ( entity, outputName ) - returns the number of array elements
    // Returns: int
    GetNumElements = function(handle, string) { return EntityOutputs.GetNumElements(handle, string) },
    // Arguments: ( entity, outputName, table, arrayElement ) - returns a table of output information
    // Returns: void
    GetOutputTable = function(handle, string, handle, int) { EntityOutputs.GetOutputTable(handle, string, handle, int) },
    // Arguments: ( entity, outputName ) - returns true if an action exists for the output
    // Returns: bool
    HasAction = function(handle, string) { return EntityOutputs.HasAction(handle, string) },
    // Arguments: ( entity, outputName ) - returns true if the output exists
    // Returns: bool
    HasOutput = function(handle, string) { return EntityOutputs.HasOutput(handle, string) },
    // Arguments: ( entity, outputName, targetName, inputName, parameter ) - remove an output from the entity
    // Returns: void
    RemoveOutput = function(handle, string, string, string, string) { EntityOutputs.RemoveOutput(handle, string, string, string, string) }
}

CScriptResponseCriteriaAPI <- {
    // Arguments: ( entity, table ) - returns a table of all criteria
    // Returns: void
    GetTable = function(handle, handle) { ResponseCriteria.GetTable(handle, handle) },
    // Arguments: ( entity, criteriaName ) - returns a string
    // Returns: string
    GetValue = function(handle, string) { return ResponseCriteria.GetValue(handle, string) },
    // Arguments: ( entity, criteriaName ) - returns true if the criterion exists
    // Returns: bool
    HasCriterion = function(handle, string) { return ResponseCriteria.HasCriterion(handle, string) }
}

CTerrorPlayerAPI <- {
    // Make the player drop an item/weapon
    // Returns: void
    DropItem = function(entity, string) { entity.DropItem(string) },
    // Extinguish a burning player
    // Returns: void
    Extinguish = function(entity) { entity.Extinguish() },
    // Try and get the current Eye Angles
    // Returns: QAngle
    EyeAngles = function(entity) { return entity.EyeAngles() },
    // Try and get the current eye position
    // Returns: Vector
    EyePosition = function(entity) { return entity.EyePosition() },
    // Get the player's active weapon
    // Returns: handle
    GetActiveWeapon = function(entity) { return entity.GetActiveWeapon() },
    // Returns the time the character has been alive (only valid when alive)
    // Returns: float
    GetAliveDuration = function(entity) { return entity.GetAliveDuration() },
    // Get the player's mask of pressed buttons
    // Returns: int
    GetButtonMask = function(entity) { return entity.GetButtonMask() },
    // Get Player Health Buffer - from pills or adrenalin etc
    // Returns: float
    GetHealthBuffer = function(entity) { return entity.GetHealthBuffer() },
    // Return the last nav area occupied - NULL if unknown
    // Returns: handle
    GetLastKnownArea = function(entity) { return entity.GetLastKnownArea() },
    // Get the player's network (i.e. Steam) ID.
    // Returns: string
    GetNetworkIDString = function(entity) { return entity.GetNetworkIDString() },
    // Get the player's name
    // Returns: string
    GetPlayerName = function(entity) { return entity.GetPlayerName() },
    // Get the player's userID.
    // Returns: int
    GetPlayerUserId = function(entity) { return entity.GetPlayerUserId() },
    // Get the current bits for the bot sense flags
    // Returns: int
    GetSenseFlags = function(entity) { return entity.GetSenseFlags() },
    // Get the Special Infected dominating this Survivor
    // Returns: handle
    GetSpecialInfectedDominatingMe = function(entity) { return entity.GetSpecialInfectedDominatingMe() },
    // Get the player's slot
    // Returns: int
    GetSurvivorSlot = function(entity) { return entity.GetSurvivorSlot() },
    // If an infected, find out what type
    // Returns: int
    GetZombieType = function(entity) { return entity.GetZombieType() },
    // Give this much ammo for your primary weapon
    // Returns: void
    GiveAmmo = function(entity, int) { entity.GiveAmmo(int) },
    // Give an item/weapon to the player
    // Returns: void
    GiveItem = function(entity, string) { entity.GiveItem(string) },
    // Give an item/weapon to the player with a skin value
    // Returns: void
    GiveItemWithSkin = function(entity, string, int) { entity.GiveItemWithSkin(string, int) },
    // Give a weapon upgrade by name
    // Returns: void
    GiveUpgrade = function(entity, int) { entity.GiveUpgrade(int) },
    // Returns true if the character has ever been injured by a member of the given team
    // Returns: bool
    HasEverBeenInjured = function(entity, int) { return entity.HasEverBeenInjured(int) },
    // Cause the vomit effect and make a player IT
    // Returns: void
    HitWithVomit = function(entity) { entity.HitWithVomit() },
    // Return true if adrenaline is active
    // Returns: bool
    IsAdrenalineActive = function(entity) { return entity.IsAdrenalineActive() },
    // Is the player dead
    // Returns: bool
    IsDead = function(entity) { return entity.IsDead() },
    // Return true if being dominated by a Special Infected
    // Returns: bool
    IsDominatedBySpecialInfected = function(entity) { return entity.IsDominatedBySpecialInfected() },
    // Player is dying, but not dead yet
    // Returns: bool
    IsDying = function(entity) { return entity.IsDying() },
    // Return true if player is firing a weapon
    // Returns: bool
    IsFiringWeapon = function(entity) { return entity.IsFiringWeapon() },
    // Return true if player is currently getting up
    // Returns: bool
    IsGettingUp = function(entity) { return entity.IsGettingUp() },
    // Is Player a Ghost
    // Returns: bool
    IsGhost = function(entity) { return entity.IsGhost() },
    // Is the player currently hanging from a ledge
    // Returns: bool
    IsHangingFromLedge = function(entity) { return entity.IsHangingFromLedge() },
    // Return true if currently IT from bile
    // Returns: bool
    IsIT = function(entity) { return entity.IsIT() },
    // Return true if currently immobilized
    // Returns: bool
    IsImmobilized = function(entity) { return entity.IsImmobilized() },
    // Return true if currently in combat
    // Returns: bool
    IsInCombat = function(entity) { return entity.IsInCombat() },
    // Is the player currently incapacitated
    // Returns: bool
    IsIncapacitated = function(entity) { return entity.IsIncapacitated() },
    // Returns whether a player is on fire
    // Returns: bool
    IsOnFire = function(entity) { return entity.IsOnFire() },
    // Return true if on third-strike
    // Returns: bool
    IsOnThirdStrike = function(entity) { return entity.IsOnThirdStrike() },
    // Return true if player is staggering
    // Returns: bool
    IsStaggering = function(entity) { return entity.IsStaggering() },
    // Returns true if falling damage is currently suppressed
    // Returns: bool
    IsSuppressingFallingDamage = function(entity) { return entity.IsSuppressingFallingDamage() },
    // On the survivor team (Otherwise, infected).
    // Returns: bool
    IsSurvivor = function(entity) { return entity.IsSurvivor() },
    // Remove a weapon upgrade by name
    // Returns: void
    RemoveUpgrade = function(entity, int) { entity.RemoveUpgrade(int) },
    // Revive a dead player by defibrillator
    // Returns: void
    ReviveByDefib = function(entity) { entity.ReviveByDefib() },
    // Revive an incapped player
    // Returns: void
    ReviveFromIncap = function(entity) { entity.ReviveFromIncap() },
    // Set Player Health Buffer - from pills or adrenalin etc
    // Returns: void
    SetHealthBuffer = function(entity, float) { entity.SetHealthBuffer(float) },
    // Set the number of times the player has been revived
    // Returns: void
    SetReviveCount = function(entity, int) { entity.SetReviveCount(int) },
    // Set the current bits for the bot sense flags - this is a SET, not an or
    // Returns: void
    SetSenseFlags = function(entity, int) { entity.SetSenseFlags(int) },
    // Sets the view angles.
    // Returns: void
    SnapEyeAngles = function(entity, QAngle) { entity.SnapEyeAngles(QAngle) },
    // Stagger a player, optionally from a vector position
    // Returns: void
    Stagger = function(entity, Vector) { entity.Stagger(Vector) },
    // Make the player switch to an item/weapon
    // Returns: bool
    SwitchToItem = function(entity, string) { return entity.SwitchToItem(string) },
    // Get a pathable location within this radius
    // Returns: Vector
    TryGetPathableLocationWithin = function(entity, float) { return entity.TryGetPathableLocationWithin(float) },
    // Cause the effect of Adrenaline - but no HP (SetHealthBuffer for that) - this is just speed!
    // Returns: void
    UseAdrenaline = function(entity, float) { entity.UseAdrenaline(float) }
}

CTerrorWeaponAPI <- {
    // Returns: int
    Clip1 = function(entity) { return entity.Clip1() },
    // Returns: int
    Clip2 = function(entity) { return entity.Clip2() },
    // Returns: int
    GetDefaultClip1 = function(entity) { return entity.GetDefaultClip1() },
    // Returns: int
    GetDefaultClip2 = function(entity) { return entity.GetDefaultClip2() },
    // Returns: int
    GetMaxClip1 = function(entity) { return entity.GetMaxClip1() },
    // Returns: int
    GetMaxClip2 = function(entity) { return entity.GetMaxClip2() },
    // Returns: void
    GiveDefaultAmmo = function(entity) { entity.GiveDefaultAmmo() },
    // Returns: bool
    Reload = function(entity) { return entity.Reload() },
    // Returns: void
    SetClip1 = function(entity, int) { entity.SetClip1(int) },
    // Returns: void
    SetClip2 = function(entity, int) { entity.SetClip2(int) }
}

ConvarsAPI <- {
    // GetClientConvarValue(name) : returns the convar value for the entindex as a string.
    // Returns: string
    GetClientConvarValue = function(string, int) { return Convars.GetClientConvarValue(string, int) },
    // GetFloat(name) : returns the convar as a float. May return null if no such convar.
    // Returns: float
    GetFloat = function(string) { return Convars.GetFloat(string) },
    // GetFloat(name) : returns the convar as a string. May return null if no such convar.
    // Returns: string
    GetStr = function(string) { return Convars.GetStr(string) },
    // SetValue(name, value) : sets the value of the convar. Supported types are bool, int, float, string.
    // Returns: void
    SetValue = function(string, value) { Convars.SetValue(string, value) }
}

DeciderAPI <- {
    // AddRule(CRule) : Add a CRule object (defined in rulescript_base.nut)
    // Returns: bool
    AddRule = function(handle) { return Decider.AddRule(handle) },
    // Binding_FindAllMatches(query,leeway) : Returns an array of all matching responses. If leeway is nonzero, all results scoring within 'leeway' of the best score return.
    // Returns: handle
    FindAllMatches = function(handle, float) { return Decider.FindAllMatches(handle, float) },
    // Binding_FindBestMatch(query) : Query the database and return the best result found. If multiple of equal score found, an arbitrary one returns.
    // Returns: handle
    FindBestMatch = function(handle) { return Decider.FindBestMatch(handle) }
}

GlobalAPI <- {
    // Adds a late bound think function to the C++ think tables for the obj
    // Returns: void
    AddThinkToEnt = function(handle, string) { ::AddThinkToEnt(handle, string) },
    // Helper for picking a random special stage based on stage_info table
    // Returns: function
    CheckForSpecialStage = function(level, stage_list, stage_info) { return ::CheckForSpecialStage(level, stage_list, stage_info) },
    // Pass a callback and default @ for it, if it doesnt exist in current table, place it there
    // Returns: function
    CheckOrSetMapCallback = function(cb_name, cb_default) { return ::CheckOrSetMapCallback(cb_name, cb_default) },
    // Remove all saved tables
    // Returns: void
    ClearSavedTables = function() { ::ClearSavedTables() },
    // Print a client message
    // Returns: void
    ClientPrint = function(handle, int, string) { ::ClientPrint(handle, int, string) },
    // Pass table - Inputs: bot, target, pos, cmd -- cmd BOT_CMD_MOVE, _ATTACK, _RETREAT, _RESET
    // Returns: bool
    CommandABot = function(handle) { return ::CommandABot(handle) },
    // Draw a debug overlay box
    // Returns: void
    DebugDrawBox = function(Vector, Vector, Vector, int, int, int, int, float) { ::DebugDrawBox(Vector, Vector, Vector, int, int, int, int, float) },
    // Draw a debug oriented box (cent, min, max, angles(p,y,r), vRgb, a, duration)
    // Returns: void
    DebugDrawBoxAngles = function(Vector, Vector, Vector, QAngle, Vector, float, float) { ::DebugDrawBoxAngles(Vector, Vector, Vector, QAngle, Vector, float, float) },
    // Draw a debug forward box (cent, min, max, forward, vRgb, a, duration)
    // Returns: void
    DebugDrawBoxDirection = function(Vector, Vector, Vector, Vector, Vector, float, float) { ::DebugDrawBoxDirection(Vector, Vector, Vector, Vector, Vector, float, float) },
    // Draw a debug circle (center, rad, vRgb, a, ztest, duration)
    // Returns: void
    DebugDrawCircle = function(Vector, Vector, float, float, bool, float) { ::DebugDrawCircle(Vector, Vector, float, float, bool, float) },
    // Try to clear all the debug overlay info
    // Returns: void
    DebugDrawClear = function() { ::DebugDrawClear() },
    // Draw a debug overlay line
    // Returns: void
    DebugDrawLine = function(Vector, Vector, int, int, int, bool, float) { ::DebugDrawLine(Vector, Vector, int, int, int, bool, float) },
    // Draw a debug line using color vec (start, end, vRgb, a, ztest, duration)
    // Returns: void
    DebugDrawLine_vCol = function(Vector, Vector, Vector, bool, float) { ::DebugDrawLine_vCol(Vector, Vector, Vector, bool, float) },
    // Draw text with a line offset
    // Returns: void
    DebugDrawScreenTextLine = function(float, float, int, string, int, int, int, int, float) { ::DebugDrawScreenTextLine(float, float, int, string, int, int, int, int, float) },
    // Draw text in 3d (origin, text, bViewCheck, duration)
    // Returns: void
    DebugDrawText = function(Vector, string, bool, float) { ::DebugDrawText(Vector, string, bool, float) },
    // Print out a table (and subtables) to the console
    // Returns: function
    DeepPrintTable = function(debugTable, prefix) { return ::DeepPrintTable(debugTable, prefix) },
    // Execute a script (internal)
    // Returns: bool
    DoIncludeScript = function(string, handle) { return ::DoIncludeScript(string, handle) },
    // Drop a fire pool from the specified location
    // Returns: void
    DropFire = function(Vector) { ::DropFire(Vector) },
    // Drop a spit pool from the specified location
    // Returns: void
    DropSpit = function(Vector) { ::DropSpit(Vector) },
    // This returns a deep copy of the passed in table
    // Returns: function
    DuplicateTable = function(srcTable) { return ::DuplicateTable(srcTable) },
    // Play named ambient sound on an entity.
    // Returns: void
    EmitAmbientSoundOn = function(string, float, int, int, handle) { ::EmitAmbientSoundOn(string, float, int, int, handle) },
    // Play named sound on Entity
    // Returns: void
    EmitSoundOn = function(string, handle) { ::EmitSoundOn(string, handle) },
    // Play named sound only on the client for the passed in player
    // Returns: void
    EmitSoundOnClient = function(string, handle) { ::EmitSoundOnClient(string, handle) },
    // Generate and entity i/o event
    // Returns: function
    EntFire = function(target, action, value, delay, activator) { return ::EntFire(target, action, value, delay, activator) },
    // Turn an entity index integer to an HScript representing that entity's script instance.
    // Returns: handle
    EntIndexToHScript = function(int) { return ::EntIndexToHScript(int) },
    // Reads a string from a file to send to script
    // Returns: string
    FileToString = function(string) { return ::FileToString(string) },
    // Returns the trigger for the rescue area
    // Returns: handle
    FindRescueAreaTrigger = function() { return ::FindRescueAreaTrigger() },
    // Fire a game event to a listening callback function in script. Parameters are passed in a squirrel table.
    // Returns: bool
    FireGameEvent = function(string, handle) { return ::FireGameEvent(string, handle) },
    // Starts the scavenge round, even if the setup timer hasn't elapsed
    // Returns: void
    ForceScavengeStart = function() { ::ForceScavengeStart() },
    // Starts the survival round, even if the survivors haven't activated the radio
    // Returns: void
    ForceSurvivalStart = function() { ::ForceSurvivalStart() },
    // Starts the versus round, even if the survivors haven't left the safe room
    // Returns: void
    ForceVersusStart = function() { ::ForceVersusStart() },
    // Gets the average flow distance of all the survivors.
    // Returns: float
    GetAverageSurvivorFlowDistance = function() { return ::GetAverageSurvivorFlowDistance() },
    // Return null if not a survivor, else the survivors 'real name'
    // Returns: string
    GetCharacterDisplayName = function(handle) { return ::GetCharacterDisplayName(handle) },
    // Gets the distance of how far the given player has made it to the goal.
    // Returns: float
    GetCurrentFlowDistanceForPlayer = function(handle) { return ::GetCurrentFlowDistanceForPlayer(handle) },
    // Gets the percentage of how far the given player has made it to the goal.
    // Returns: float
    GetCurrentFlowPercentForPlayer = function(handle) { return ::GetCurrentFlowPercentForPlayer(handle) },
    // Returns the current difficulty as a numeric value.
    // Returns: int
    GetDifficulty = function() { return ::GetDifficulty() },
    // Returns the current difficulty as a string.
    // Returns: string
    GetDifficultyString = function() { return ::GetDifficultyString() },
    // Gets distance from the start of the map for a given position.
    // Returns: float
    GetFlowDistanceForPosition = function(Vector) { return ::GetFlowDistanceForPosition(Vector) },
    // Gets the percent of where in the flow a given position is.
    // Returns: float
    GetFlowPercentForPosition = function(Vector, bool) { return ::GetFlowPercentForPosition(Vector, bool) },
    // Returns the engines current frame count
    // Returns: int
    GetFrameCount = function() { return ::GetFrameCount() },
    // Returns the Friction on a player entity, meaningless if not a player
    // Returns: float
    GetFriction = function(handle) { return ::GetFriction(handle) },
    // Fill passed in table with current stats about infected in the world
    // Returns: void
    GetInfectedStats = function(handle) { ::GetInfectedStats(handle) },
    // Put Player's inventory data into a passed in table
    // Returns: void
    GetInvTable = function(handle, handle) { ::GetInvTable(handle, handle) },
    // Get the local player on a listen server.
    // Returns: handle
    GetListenServerHost = function() { return ::GetListenServerHost() },
    // Gets the max flow distance for the entire map.
    // Returns: float
    GetMaxFlowDistance = function() { return ::GetMaxFlowDistance() },
    // Returns the index of the named model.
    // Returns: int
    GetModelIndex = function(string) { return ::GetModelIndex(string) },
    // Get Angular Velocity for VPHYS or normal object
    // Returns: Vector
    GetPhysAngularVelocity = function(handle) { return ::GetPhysAngularVelocity(handle) },
    // Get Velocity for VPHYS or normal object
    // Returns: Vector
    GetPhysVelocity = function(handle) { return ::GetPhysVelocity(handle) },
    // Given a character type, return the entity, or null
    // Returns: handle
    GetPlayerFromCharacter = function(int) { return ::GetPlayerFromCharacter(int) },
    // Given a user id, return the entity, or null
    // Returns: handle
    GetPlayerFromUserID = function(int) { return ::GetPlayerFromUserID(int) },
    // Returns number of Scavenge items needed.
    // Returns: int
    GetScavengeItemsGoal = function() { return ::GetScavengeItemsGoal() },
    // Returns number of Scavenge items remaining.
    // Returns: int
    GetScavengeItemsRemaining = function() { return ::GetScavengeItemsRemaining() },
    // Returns float duration of the sound. Takes soundname and optional actormodelname.
    // Returns: float
    GetSoundDuration = function(string, string) { return ::GetSoundDuration(string, string) },
    // Manage the system timers
    // Returns: void
    HUDManageTimers = function(int, int, float) { ::HUDManageTimers(int, int, float) },
    // Place the HUD element for Slot at X,Y,W,H
    // Returns: void
    HUDPlace = function(int, float, float, float, float) { ::HUDPlace(int, float, float, float, float) },
    // Read value from a system timer
    // Returns: float
    HUDReadTimer = function(int) { return ::HUDReadTimer(int) },
    // Pass the HUD definition table for your mode
    // Returns: void
    HUDSetLayout = function(handle) { ::HUDSetLayout(handle) },
    // Returns true if the mode has more than a single difficulty.
    // Returns: bool
    HasConfigurableDifficultySetting = function() { return ::HasConfigurableDifficultySetting() },
    // Does the current game mode have humans playing as zombies?
    // Returns: bool
    HasPlayerControlledZombies = function() { return ::HasPlayerControlledZombies() },
    // Returns true if this server is a dedicated server.
    // Returns: bool
    IsDedicatedServer = function() { return ::IsDedicatedServer() },
    // True if the current map is the final map of the campaign
    // Returns: bool
    IsMissionFinalMap = function() { return ::IsMissionFinalMap() },
    // Checks if the modelname is precached.
    // Returns: bool
    IsModelPrecached = function(string) { return ::IsModelPrecached(string) },
    // Is this player/entity a bot
    // Returns: bool
    IsPlayerABot = function(handle) { return ::IsPlayerABot(handle) },
    // Takes a sound name
    // Returns: bool
    IsSoundPrecached = function(string) { return ::IsSoundPrecached(string) },
    // Fills out a table with the local time (second, minute, hour, day, month, year, dayofweek, dayofyear, daylightsavings)
    // Returns: void
    LocalTime = function(handle) { ::LocalTime(handle) },
    // Have a player pickup a nearby named entity
    // Returns: void
    PickupObject = function(handle, handle) { ::PickupObject(handle, handle) },
    // Get a script instance of a player by index.
    // Returns: handle
    PlayerInstanceFromIndex = function(int) { return ::PlayerInstanceFromIndex(int) },
    // Precache an entity from KeyValues in table
    // Returns: bool
    PrecacheEntityFromTable = function(handle) { return ::PrecacheEntityFromTable(handle) },
    // Precache a model.
    // Returns: int
    PrecacheModel = function(string) { return ::PrecacheModel(string) },
    // Precache a sound.
    // Returns: void
    PrecacheSound = function(string) { ::PrecacheSound(string) },
    // (hEntity, szConcept, flDelay, szCriteria) Queue a speech concept
    // Returns: void
    QueueSpeak = function(handle, string, float, string) { ::QueueSpeak(handle, string, float, string) },
    // Generate a random floating point number within a range, inclusive
    // Returns: float
    RandomFloat = function(float, float) { return ::RandomFloat(float, float) },
    // Generate a random integer within a range, inclusive
    // Returns: int
    RandomInt = function(int, int) { return ::RandomInt(int, int) },
    // Apply passed flags to passed infected or all commons if 2nd param is null
    // Returns: void
    ReapplyInfectedFlags = function(int, handle) { ::ReapplyInfectedFlags(int, handle) },
    // Register as a listener for a game event from script.
    // Returns: void
    RegisterScriptGameEventListener = function(string) { ::RegisterScriptGameEventListener(string) },
    // Reloads the MotD file
    // Returns: void
    ReloadMOTD = function() { ::ReloadMOTD() },
    // Put saved data back into the passed in table
    // Returns: void
    RestoreTable = function(string, handle) { ::RestoreTable(string, handle) },
    // Rotate a QAngle by another QAngle.
    // Returns: QAngle
    RotateOrientation = function(QAngle, QAngle) { return ::RotateOrientation(QAngle, QAngle) },
    // Rotate a Vector around a point.
    // Returns: Vector
    RotatePosition = function(Vector, QAngle, Vector) { return ::RotatePosition(Vector, QAngle, Vector) },
    // (hVictim, flRange) Make all common zombies in range rush the victim
    // Returns: void
    RushVictim = function(handle, float) { ::RushVictim(handle, float) },
    // Save the passed in table
    // Returns: void
    SaveTable = function(string, handle) { ::SaveTable(string, handle) },
    // Have Entity say string, and teamOnly or not
    // Returns: void
    Say = function(handle, string, bool) { ::Say(handle, string, bool) },
    // Start a screenfade with the following parameters. player, red, green, blue, alpha, flFadeTime, flFadeHold, flags
    // Returns: void
    ScreenFade = function(handle, int, int, int, int, float, float, int) { ::ScreenFade(handle, int, int, int, int, float, float, int) },
    // Start a screenshake with the following parameters. vecCenter, flAmplitude, flFrequency, flDuration, flRadius, eCommand( SHAKE_START = 0, SHAKE_STOP = 1 ), bAirShake
    // Returns: void
    ScreenShake = function(Vector, float, float, float, float, int, bool) { ::ScreenShake(Vector, float, float, float, float, int, bool) },
    // Makes the passed in call to g_MapScript and g_ModeScript, but it must have Zero args
    // Returns: function
    ScriptMode_SystemCall = function(callname) { return ::ScriptMode_SystemCall(callname) },
    // Pass a lambda to this, it will get called once as part of next Update, for doing something 'soon but not now'
    // Returns: function
    ScriptedMode_CallNextUpdate = function(callnext) { return ::ScriptedMode_CallNextUpdate(callnext) },
    // Send a string to the console as a client command
    // Returns: void
    SendToConsole = function(string) { ::SendToConsole(string) },
    // Send a string to the console as a server command
    // Returns: void
    SendToServerConsole = function(string) { ::SendToServerConsole(string) },
    // Sets a USERINFO client ConVar for a fakeclient
    // Returns: void
    SetFakeClientConVarValue = function(handle, string, string) { ::SetFakeClientConVarValue(handle, string, string) },
    // Set the number of Scavenge items needed.
    // Returns: void
    SetScavengeItemsGoal = function(int) { ::SetScavengeItemsGoal(int) },
    // Set the number of Scavenge items remaining.
    // Returns: void
    SetScavengeItemsRemaining = function(int) { ::SetScavengeItemsRemaining(int) },
    // Print a hud message on all clients
    // Returns: void
    ShowMessage = function(string) { ::ShowMessage(string) },
    // Spawn entity from KeyValues in table - 'name' is entity name, rest are KeyValues for spawn.
    // Returns: handle
    SpawnEntityFromTable = function(string, handle) { return ::SpawnEntityFromTable(string, handle) },
    // Hierarchically spawn an entity group from a set of spawn tables.
    // Returns: bool
    SpawnEntityGroupFromTable = function(handle) { return ::SpawnEntityGroupFromTable(handle) },
    // Auto-create a startbox that will give you a callback when the first player exits it
    // Returns: function
    SpawnStartBox = function(centerobjname, useFloating, width, depth, barriermodel, min_gap) { return ::SpawnStartBox(centerobjname, useFloating, width, depth, barriermodel, min_gap) },
    // Execute a stage table, i.e. move parameters to DirectorOptions, do callbacks and so on
    // Returns: function
    StageInfo_Execute = function(stageInfo, stageDefaults) { return ::StageInfo_Execute(stageInfo, stageDefaults) },
    // Tells all existing nextbots to swap into assault mode and not hide/dither/loiter
    // Returns: void
    StartAssault = function() { ::StartAssault() },
    // Stop named ambient sound on an entity.
    // Returns: void
    StopAmbientSoundOn = function(string, handle) { ::StopAmbientSoundOn(string, handle) },
    // Stop named sound on Entity
    // Returns: void
    StopSoundOn = function(string, handle) { ::StopSoundOn(string, handle) },
    // Store a string to a file for later reading
    // Returns: bool
    StringToFile = function(string, string) { return ::StringToFile(string, string) },
    // Teleport players to start entities named by the argument - must have 4 spawnpoints
    // Returns: function
    TeleportPlayersToStartPoints = function(spawnpointName) { return ::TeleportPlayersToStartPoints(spawnpointName) },
    // adds ticker data to a passed in HUDTable
    // Returns: function
    Ticker_AddToHud = function(hudTable, strInit, blink) { return ::Ticker_AddToHud(hudTable, strInit, blink) },
    // sets the current Ticker string, w/an optional timeout value
    // Returns: function
    Ticker_NewStr = function(newStr, newTimeout) { return ::Ticker_NewStr(newStr, newTimeout) },
    // Get the current server time
    // Returns: float
    Time = function() { return ::Time() },
    // Convert a # of seconds to a displayable time string form m:ss
    // Returns: function
    TimeToDisplayString = function(disp_time) { return ::TimeToDisplayString(disp_time) },
    // Pass table - Inputs: start, end, mask, ignore  -- outputs: pos, fraction, hit, enthit, startsolid
    // Returns: bool
    TraceLine = function(handle) { return ::TraceLine(handle) },
    // Generate a string guaranteed to be unique across the life of the script VM, with an optional root string. Useful for adding data to tables when not sure what keys are already in use in that table.
    // Returns: function
    UniqueString = function(string) { return ::UniqueString(string) },
    // Does a z_spawn like spawn based on an input table
    // Returns: bool
    ZSpawn = function(handle) { return ::ZSpawn(handle) },
    // Add a rule to the decision database.
    // Returns: bool
    rr_AddDecisionRule = function(handle) { return ::rr_AddDecisionRule(handle) },
    // Commit the result of QueryBestResponse back to the given entity to play. Call with params (entity, airesponse)
    // Returns: bool
    rr_CommitAIResponse = function(handle, handle) { return ::rr_CommitAIResponse(handle, handle) },
    // Retrieve a table of all available expresser targets, in the form { name : handle, name: handle }.
    // Returns: handle
    rr_GetResponseTargets = function() { return ::rr_GetResponseTargets() },
    // Params: (entity, query) : tests 'query' against entity's response system and returns the best response found (or null if none found).Function:    array
    // Returns: handle
    rr_QueryBestResponse = function(handle, handle) { return ::rr_QueryBestResponse(handle, handle) },
    // Throws an exception if exp is evaluated to false.
    // Returns: void
    assert = function(bool) { ::assert(bool) },
    // Returns the currently running closure.
    // Returns: function
    callee = function() { return ::callee() },
    // Runs the garbage collector and returns the number of reference cycles found(and deleted) This function only works on garbage collector builds.
    // Returns: int
    collectgarbage = function() { return ::collectgarbage() },
    // Compiles a string containing a squirrel script into a function and returns it.
    // Returns: function
    compilestring = function(string, string) { return ::compilestring(string, string) },
    // Enable/disable the debug line information generation at compile time. enable != null enables . enable == null disables.
    // Returns: void
    enabledebuginfo = function(any) { ::enabledebuginfo(any) },
    // Prints x in the standard error output.
    // Returns: void
    error = function(string) { ::error(string) },
    // Returns the const table of the VM.
    // Returns: table
    getconsttable = function() { return ::getconsttable() },
    // Returns the root table of the VM.
    // Returns: table
    getroottable = function() { return ::getroottable() },
    // Returns the stack frame informations at the given stack level (0 is the current function 1 is the caller and so on). If the stack level doesn't exist the function returns null.
    // Returns: table
    getstackinfos = function(int) { return ::getstackinfos(int) },
    // Prints message to console without any line feed after.
    // Returns: void
    print = function(string) { ::print(string) },
    // Runs the garbage collector and returns an array containing all unreachable object found. If no unreachable object is found, null is returned instead. This function is meant to help debugging reference cycles. This function only works on garbage collector builds.
    // Returns: array
    resurrectunreachable = function() { return ::resurrectunreachable() },
    // Sets the const table of the VM which also returns the previous const table.
    // Returns: table
    setconsttable = function(table) { return ::setconsttable(table) },
    // Sets the runtime error handler.
    // Returns: void
    seterrorhandler = function(func) { ::seterrorhandler(func) },
    // Sets the root table of the VM which also returns the previous root table.
    // Returns: table
    setroottable = function(table) { return ::setroottable(table) },
    // Suspends the coroutine that called this function.
    // Returns: void
    suspend = function(any) { ::suspend(any) },
    // Return the 'raw' type of an object without invoking the metatmethod '_typeof'.
    // Returns: string
    type = function(any) { return ::type(any) },
    // Returns the absolute value of x as an integer.
    // Returns: int
    abs = function(float) { return ::abs(float) },
    // Returns the arccosine of x.
    // Returns: float
    acos = function(float) { return ::acos(float) },
    // Returns the arcsine of x.
    // Returns: float
    asin = function(float) { return ::asin(float) },
    // Returns the arctangent of x.
    // Returns: float
    atan = function(float) { return ::atan(float) },
    // Returns the arctangent of x/y. Unlike atan, it does not lose quadrant information.
    // Returns: float
    atan2 = function(float, float) { return ::atan2(float, float) },
    // Returns a float value representing the smallest integer that is greater than or equal to x.
    // Returns: float
    ceil = function(float) { return ::ceil(float) },
    // Returns the cosine of x.
    // Returns: float
    cos = function(float) { return ::cos(float) },
    // Returns the exponential value (e^x) of the float parameter x.
    // Returns: float
    exp = function(float) { return ::exp(float) },
    // Returns the absolute value of x as a float.
    // Returns: float
    fabs = function(float) { return ::fabs(float) },
    // Returns a float value representing the largest integer that is less than or equal to x.
    // Returns: float
    floor = function(float) { return ::floor(float) },
    // Returns the natural logarithm of x.
    // Returns: float
    log = function(float) { return ::log(float) },
    // Returns the logarithm base-10 of x.
    // Returns: float
    log10 = function(float) { return ::log10(float) },
    // Returns x raised to the power of y.
    // Returns: float
    pow = function(float, float) { return ::pow(float, float) },
    // Returns a pseudorandom integer in the range 0 to RAND_MAX.
    // Returns: int
    rand = function() { return ::rand() },
    // Returns the sine of x.
    // Returns: float
    sin = function(float) { return ::sin(float) },
    // Returns the square root of x.
    // Returns: float
    sqrt = function(float) { return ::sqrt(float) },
    // Sets the starting point for generating a series of pseudorandom integers.
    // Returns: void
    srand = function(float) { ::srand(float) },
    // Returns the tangent of x.
    // Returns: float
    tan = function(float) { return ::tan(float) },
    // Returns a formatted string. Same rules as the standard C functions (except * is not supported).
    // Returns: string
    format = function(string, ...) {
        local args = [null, string]; args.extend(vargv)
        return ::format.acall(args)
    },
    // Removes whitespace characters at the beginning of the given string.
    // Returns: string
    lstrip = function(string) { return ::lstrip(string) },
    // Removes whitespace characters at the end of the given string.
    // Returns: string
    rstrip = function(string) { return ::rstrip(string) },
    // Returns an array of strings split at each point where a separator character occurs in str. The separator is not returned as part of any array element. the parameter separators is a string that specifies the characters as to be used for the splitting.
    // Returns: array
    split = function(string, string) { return ::split(string, string) },
    // Removes whitespace characters at both the beginning and end of the given string.
    // Returns: string
    strip = function(string) { return ::strip(string) }
}